ARG VER=15.4
FROM ramirezfx/opensuse-leap-kde-baseimage:$VER
ENV SHELL=/bin/bash

# Install minimum needed packages
RUN zypper -n in git cups wget

# Download and install latest Nomachine
RUN wget -O /tmp/nomachine.rpm "https://www.nomachine.com/free/linux/64/rpm" && zypper -n --no-gpg-checks in /tmp/nomachine.rpm
# RUN DLLINK=$(wget --save-headers --output-document - https://downloads.nomachine.com/de/download/?id=6 | grep download.nomachine.com | cut -d '"' -f6 | head -1) && wget -O /tmp/nomachine.rpm $DLLINK && zypper -n --no-gpg-checks in /tmp/nomachine.rpm

# ADD nxserver.sh
RUN wget -O /nxserver.sh https://raw.githubusercontent.com/ramirezfx/opensuse-leap-desktop/main/nxserver.sh && chmod +x /nxserver.sh

# Custom Packages And Sripts:
RUN wget -O /custom.sh https://raw.githubusercontent.com/ramirezfx/opensuse-leap-desktop/main/custom.sh && chmod +x /custom.sh
RUN /custom.sh

# Add language-support:
RUN wget -O /tmp/languages.txt https://github.com/ramirezfx/opensuse-leap-desktop/raw/main/lang-kde.txt && xargs -a /tmp/languages.txt zypper -n --no-gpg-checks in

ENTRYPOINT ["/nxserver.sh"]
